MyPage/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyProfile.urls')),
]

MyProfile/urls.py
from django.urls import path
from . import views

app_name = 'MyProfile'

urlpatterns = [
    path('', views.index, name='index'),
    path('moreaboutme/', views.moreaboutme, name='moreaboutme'),
    path('skill/', views.skill, name='skill'),
    path('agenda_input/', views.agenda_input, name='agenda-input'),
    path('agenda_view/', views.agenda_view, name='agenda-view'),
    path('agenda_delete/<id>', views.delete_agenda, name="agenda-delete")
]

MyProfile/models.py
from django.db import models
from datetime import date
# Create your models here.

class Agenda(models.Model):
    date = models.DateField()
    day = models.CharField(max_length=60)
    hour = models.TimeField()
    activity = models.CharField(max_length=60)
    location = models.CharField(max_length=60)
    category = models.CharField(max_length=60)

MyProfile/forms.py
from django import forms
from .models import Agenda

class CreateAgendaForm(forms.Form):
    date_attrs = {
        'type':'date',
        'class': 'form-control',
    }

    hour_attrs = {
        'type':'time',
        'class': 'form-control',
    }

    activity_attrs = {
        'type':'text',
        'class': 'form-control',
        'placeholder':'Nama kegiatan...'
    }

    location_attrs = {
        'type':'text',
        'class': 'form-control',
        'placeholder':'Nama tempat...'
    }

    category_attrs = {
        'type':'text',
        'class': 'form-control',
        'placeholder':'Nama kategori....'
    }

    date = forms.DateTimeField(label='Date', required=True, localize=True, widget=forms.DateInput(attrs=date_attrs))
    hour = forms.TimeField(label='Hour', required=True, localize=True, widget=forms.TimeInput(attrs=hour_attrs))
    activity = forms.CharField(label='Activity', max_length=60,  required=True, widget=forms.TextInput(attrs=activity_attrs))
    location = forms.CharField(label='Location', max_length=60, required=True, widget=forms.TextInput(attrs=location_attrs))
    category = forms.CharField(label='Category', max_length=60, required=True, widget=forms.TextInput(attrs=category_attrs))

class CustomModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "{}: {}, {}".format(obj.activity, obj.day, obj.date)

class DeleteAgendaForm(forms.Form):
    choice_attrs = {
        'class':'custom-select'
    }

    agendas = Agenda.objects.all()
    choice = CustomModelChoiceField(label="Activity", required=True, widget=forms.Select(choice_attrs), queryset=agendas, to_field_name="activity")

MyProfile/views.py
from django.shortcuts import render, redirect
from .forms import CreateAgendaForm, DeleteAgendaForm
from .models import Agenda
# Create your views here.

def index(request):
    return render(request, 'index.html')

def moreaboutme(request):
    return render(request, 'moreaboutme.html')

def skill(request):
    return render(request, 'skill.html')

def agenda_input(request):
    form = CreateAgendaForm()

    if(request.method == 'POST'):
        form = CreateAgendaForm(request.POST)
        if (form.is_valid()):
            date = form.cleaned_data['date']
            day = date.strftime('%A')
            hour = form.cleaned_data['hour']
            activity = form.cleaned_data['activity']
            location = form.cleaned_data['location']
            category = form.cleaned_data['category']
            

            agenda = Agenda(
                date = date,
                day = day,
                hour = hour,
                activity = activity,
                location = location,
                category = category
            )

            agenda.save()
            return redirect("MyProfile:agenda-view")

    response = {'create_agenda_form': form} #'delete_agenda_form': DeleteAgendaForm}
    
    return render(request, 'agenda-input.html', response)

def save_jadwal(request):
    response = {'save_status':''}
    if(request.method == 'POST'):
        form = CreateAgendaForm(request.POST)
        if (form.is_valid()):
            date = form.cleaned_data['date']
            day = date.strftime('%A')
            hour = form.cleaned_data['hour']
            activity = form.cleaned_data['activity']
            location = form.cleaned_data['location']
            category = form.cleaned_data['category']
            

            agenda = Agenda(
                date = date,
                day = day,
                hour = hour,
                activity = activity,
                location = location,
                category = category
            )

            agenda.save()

            response['save_status'] = 'ooh yeah ooh yea'
        else:
            response['save_status'] = 'thats a bruh moment'
    else:
        response['save_status'] = 'uwu'

    return render(request, 'saved.html', response)

def delete_agenda(request, id):
    # response = {'delete_status':''}
    # if(request.method == 'POST'):
    #     form = DeleteAgendaForm(request.POST)
    #     if (form.is_valid()):
    #         agenda = form.cleaned_data['choice']
    #         agenda.delete()

    #         response['delete_status'] = 'snap'
    #     else:
    #         response['delete_status'] = 'sike'
    # else:
    #     response['delete_status'] = 'uwu, idk man idk why it happened like this im sorry'

    # return render(request, 'deleted.html', response)
    deleted_agenda = Agenda.objects.get(id=id)
    deleted_agenda.delete()
    return redirect("MyProfile:agenda-view")

def agenda_view(request):
    agendas = Agenda.objects.all()

    response = {'agendas':agendas}
    return render(request, 'agenda-view.html', response)



#def agenda_input(request):
#    return render(request, 'agenda-input.html')

#def agenda_view(request):
#    return render(request, 'agenda-view.html')

MyProfile/templates/agenda-input.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title> Timothy Regana Tarigan </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
      {% include 'navbar.html' %}
    <form method="post">
        {% csrf_token %}
        {{ create_agenda_form }}
        <input type="submit" value="Create agenda">
    </form>

MyProfile/templates/agenda-view.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title> Timothy Regana Tarigan </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
      {% include 'navbar.html' %}
      <h1>uwu</h1>
      {% for agenda in agendas %}
    <div>
        <p>{{agenda.date}}</p>
        <p>{{agenda.day}}</p>
        <p>{{agenda.hour}}</p>
        <p>{{agenda.activity}}</p>
        <p>{{agenda.location}}</p>
        <p>{{agenda.category}}</p>
        <a href="{% url 'MyProfile:agenda-delete' id=agenda.id %}"><button>delete</button></a>
    </div>
      {%endfor%}

MyProfile/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title> Timothy Regana Tarigan </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
      {% include 'navbar.html' %}
        <div class="container-fluid">
            <div class="row intro bg1">
                <div class="col-md-2 ">
                    <h1> HELLO!</h1>
                    <img src="{% static 'images/profile.png'%}" alt="It's Me!" class="center" width="300" height="300">
                    <p style="letter-spacing: 4px"> TIMOTHY <br> REGANA <br> TARIGAN </p>

                </div>
                <div class="col-md-5 abt desc my-auto offset-md-1">
                    <p class=about> ABOUT ME </p><br>
                    <a href="{% url 'MyProfile:moreaboutme' %}" target="_blank"><p style="margin-top: 0; font-size:30px;"> (and more!) </p></a>
                    <hr style="height: 4px; background: black; margin-top: 0px;">
                    <p style="color:white" class="desc">Right now, I'm a Computer Science student in Universitas Indonesia.<br> 
                        Japanese culture enthusiast, lover of football (Liverpool!) and esports. <br>
                        I also play music, mainly piano and vocals.</p>
                </div>
                <div class="col-md-3 abt desc my-auto offset-md-1 text-center">
                    <p class="about"> CONTACT ME</p>
                    <hr style="height: 4px; background: black; margin-top: 0px;">
                    <img src="{% static 'images/gmail.png'%}" width="100" height="100" hspace="20">
                    <p style="font-size: 20px; text-align: center" class="desc">timothyregana@gmail.com</p>
                    <img src="{% static 'images/insta.png'%}" width="100" height="100" hspace="20">
                    <p style="font-size: 20px; text-align: center" class="desc">phazeblaze</p>
                    <img src="{% static 'images/line.png'%}" width="100" height="100" hspace="20">
                    <p style="font-size: 20px; text-align: center" class="desc">phazeblade</p>
                </div>
            </div>
 



        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
    <br>
    <br>
    </body>
    
</html>

MyProfile/templates/moreaboutme.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
            {% load static %}
            <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <title> Timothy, but more </title>
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container-fluid">
            <div class="row bg1">
            <div class="col-12">
            <div class="row intro">
                <div class="col-md-6 offset-md-1">
                        <p> My Biodata </p>
                        <img src="{% static 'images/profile.png'%}" alt="It's Me!" class="center" width="300" height="300">
                </div>
            </div>
            <div class="row desc" style="color:aliceblue;">
                <div class="col-md-10 offset-md-1">
                    <p>Name         : Timothy Regana Tarigan</p>
                    <p>Nickname     : Timo, Timot, phaze (online)</p>
                    <p>Date of Birth: 24th of October</p>
                    <p>Hobby        : Gaming, Music, Reading, being stupid</p>
                    <p>Waifu        : Jeanne Alter, Saber Alter</p>
                    <br>
                    <br>
                </div>
            </div>
            </div>
            </div>
            <div class="row bg1">
            <div class="col-12">
            <div class="row intro">
                <div class="col-md-6 offset-md-1">
                    <p>RAMBLINGS</p>
                </div>
            </div>
            <div class="row moredesc">
                <div class="col-md-10 offset-md-1">
                    <p>tfw you realize you must use bootstrap when youre done with your website </p>
                    <p>muhammad ali went back to his hometown, muhammad kembali</p>
                    <p>if you've opened my instagram, i apologize</p>
                    <p>tfw you see people using navbar</p>
                    <p>gacha is a drug, no dont take my money please dont give me more cute girl i havent eaten in 3 months</p>
                    <p>this is basically filler and a time waster</p>
                    <p>if you put a bit of effort, it is actually quite easy to cosplay as Kak Pewe</p>
                    <p>if youre still reading this, youre awesome and keep fighting</p>
                    <p>machine learning is just a spicy if else</p>
                    <p>i enjoy my code like i enjoy my italian meal, spaghetti</p>
                    <p>nothing wrong with liking a fictional character, just wish you have the same dedication to studying</p>
                    <p>liiiiiiiiverpoool, liiiiiiiiverpoool will win the league title this year because this year is our year</p>
                    <p>this would be a good time to promote my soundcloud, its a shame that theres nothing worthwhile in it</p>
                    <p>medusa from fate is the one waifu people dont know they want</p>
                    

                </div>
            </div>
            </div>
            </div>
    </body>
</html>

MyProfile/templates/navbar.html
<!DOCTYPE html>
<html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title> My Skills </title>
        <link rel="stylesheet" href="style.css">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">MyPage</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'MyProfile:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'MyProfile:moreaboutme' %}" >More About Me</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'MyProfile:skill' %}" >Skills and Experience</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'MyProfile:agenda-input' %}" >Make Agenda</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'MyProfile:agenda-view' %}" >See Agenda</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">hello world</a>
                </li>
              </ul>
            </div>
          </nav>
    </body>    
</html>

MyProfile/templates/skill.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Bree+Serif&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title> My Skills </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
        {% include 'navbar.html' %}
        <div class="container-fluid">
            <div class="row bg1">
            <div class="col-12">
                <div class="row about text-center">
                <div class="col-md-12">
                    <p style="text-align:center"> SKILLS </p>
                    <img src="{% static 'images/java1.png'%}" width="100" height="100" hspace="20"> <!--java icon-->
                    <p class="exp"> Finished basic training course in Java</p>
                    <img src="{% static 'images/python1.png'%}" width="100" height="100" hspace="20"> <!--python icon-->
                    <p class="exp"> Finished basic training course in Python</p>
                    <img src="{% static 'images/music1.png'%}" width="100" height="100" hspace="20"> <!--music icon-->
                    <p class="exp"> Have experience in performing as a keyboardist and backing vocalist</p>
                    <img src="{% static 'images/camera1.png'%}" width="100" height="100" hspace="20"> <!--photography icon-->
                    <p class="exp"> Worked as a photographer in few school events </p>
                    <img src="{% static 'images/english1.png'%}" width="100" height="100" hspace="20"> <!--english icon-->
                    <p class="exp"> Fluent in English, able to communicate well in English</p>
                </div>
                </div>

                <div class="row about text-center">
                <div class="col-md-12">
                    <p style="text-align:center"> EXPERIENCE </p>
                    <p class="exp"> Was a member of my junior high school's Student Council</p>
                    <p class="exp"> Involved in some of my high school's events as a member of documentation section</p>
                    <p class="exp"> Now studying in Universitas Indonesia's Faculty of Computer Science</p>
                </div>
                </div>

            </div>
            </div>
        </div>